name: spring deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'

jobs:
  deploy_spring:
    runs-on: ubuntu-latest
    steps:
      - name: clone terraform project
        run: |
          git clone https://github.com/ChazTech3030/wmca_terraform_demo.git
          cd ./wmca_terraform_demo
          terraform init


